# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import synonyms_data_pb2 as synonyms__data__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in synonyms_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SynonymServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addSynonym = channel.unary_unary(
                '/synonyms_data.SynonymService/addSynonym',
                request_serializer=synonyms__data__pb2.SynonymDataRequest.SerializeToString,
                response_deserializer=synonyms__data__pb2.SynonymDataResponse.FromString,
                _registered_method=True)


class SynonymServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def addSynonym(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SynonymServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addSynonym': grpc.unary_unary_rpc_method_handler(
                    servicer.addSynonym,
                    request_deserializer=synonyms__data__pb2.SynonymDataRequest.FromString,
                    response_serializer=synonyms__data__pb2.SynonymDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'synonyms_data.SynonymService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('synonyms_data.SynonymService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SynonymService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def addSynonym(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synonyms_data.SynonymService/addSynonym',
            synonyms__data__pb2.SynonymDataRequest.SerializeToString,
            synonyms__data__pb2.SynonymDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
