# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: synonyms_data.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'synonyms_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13synonyms_data.proto\x12\rsynonyms_data\"&\n\x07Synonym\x12\x0e\n\x06origin\x18\x01 \x01(\t\x12\x0b\n\x03new\x18\x02 \x01(\t\"L\n\x12SynonymDataRequest\x12\x0c\n\x04time\x18\x01 \x01(\t\x12(\n\x08synonyms\x18\x02 \x03(\x0b\x32\x16.synonyms_data.Synonym\"6\n\x13SynonymDataResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2e\n\x0eSynonymService\x12S\n\naddSynonym\x12!.synonyms_data.SynonymDataRequest\x1a\".synonyms_data.SynonymDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'synonyms_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNONYM']._serialized_start=38
  _globals['_SYNONYM']._serialized_end=76
  _globals['_SYNONYMDATAREQUEST']._serialized_start=78
  _globals['_SYNONYMDATAREQUEST']._serialized_end=154
  _globals['_SYNONYMDATARESPONSE']._serialized_start=156
  _globals['_SYNONYMDATARESPONSE']._serialized_end=210
  _globals['_SYNONYMSERVICE']._serialized_start=212
  _globals['_SYNONYMSERVICE']._serialized_end=313
# @@protoc_insertion_point(module_scope)
